language: node_js
node_js:
  - 9
install:
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/framework.git unitejs/unitejs-framework
  - cd unitejs/unitejs-framework
  - npm link
  - cd ../../
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp coveralls || travis_terminate 1
